apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hapi-fhir-open-emr.fullname" . }}
  labels:
    {{- include "hapi-fhir-open-emr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hapi-fhir-open-emr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hapi-fhir-open-emr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hapi-fhir-open-emr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:      
          - name: SPRING_PROFILE
            value: dev
          - name: SPRING_APPLICATION_JSON
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: dev-config.json
          - name: token_url
            value: {{ .Values.openemr.token_url }}
          - name: api_url
            value: {{ .Values.openemr.api_url }}
          - name: client_id
            value: {{ .Values.openemr.client_id }}
          - name: grant_type
            value: {{ .Values.openemr.grant_type }}
          - name: user_role
            value: {{ .Values.openemr.user_role }}
          - name: scope
            value: {{ .Values.openemr.scope }}
          - name: username
            value: {{ .Values.openemr.username }}
          - name: password
            value: {{ .Values.openemr.password }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080 
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        
