apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "spring.datasource.url": "jdbc:postgresql://hapi-fhir-open-emr-postgresql.default.svc.cluster.local:5432/hapi-persist-db",
      "spring.datasource.username": "postgres",
      "spring.datasource.password": "postgres"
     }'